export const ALL_HEROES_REQUEST = 'ALL_HEROES_REQUEST'
export const ALL_HEROES_SUCCESS = 'ALL_HEROES_SUCCESS'

export const SINGLE_HEROE_REQUEST = 'SINGLE_HEROE_REQUEST'
export const SINGLE_HEROE_SUCCESS = 'SINGLE_HEROE_SUCCESS'

export const ALL_COMICS_REQUEST = 'ALL_COMICS_REQUEST'
export const ALL_COMICS_SUCCESS = 'ALL_COMICS_SUCCESS'

export const SINGLE_COMIC_REQUEST = 'SINGLE_COMIC_REQUEST'
export const SINGLE_COMIC_SUCCESS = 'SINGLE_COMIC_SUCCESS'
